<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

In [1]:
import numpy as np

1. _Subsetting is using either indexing or slicing to create a subset of data you want to work with_
1. Indexing is selecting 1 data from an array or a list
1. _Slicing is selecting a range of data from the array or list._
1. Masking is a tool for arrays to select data following a specific condition.

In [2]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [27]:
np_numbers = np_array_2d[:,0]

np_numbers_remainder = np_numbers.astype(int) % 2

np_array_2d[np_numbers_remainder == 1][:, 1]




array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

In [73]:
py_list = [[66, 50, 57, -1, -1],
               [92, -1, 88, -1, -1],
               [75, -1, -1, 76, -1],
               [-1, 51, 87, -1, -1],
               [71, -1, 67, -1, 69]]

np_array= np.array(py_list)

mymask = np_array >50 #more than 50
mymask2 = np_array < 50 #less than 50
mymask3 = np_array == 50 #equal to 50

np_array[mymask] = 1
np_array[mymask2] = -1 
np_array[mymask3] = 0
print(np_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
