<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

In [1]:
import numpy as np

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [13]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = py_list

x[0]  # Accessing the first element of the list
x[1]  # Accessing the second element of the list
x[0:3]  # Slicing the first three elements of the list
x[1:5]  # Slicing from the second to the fifth element of the list
x[1:6:2]  # Slicing from the second to the sixth element with a step of 2
x[5:]  # Slicing from the sixth element to the end of the list
x[:5]  # Slicing from the start to the fifth element of the list
x[5:2:-1]  # Slicing from the sixth to the third element in reverse order
x[::-1]  # Reversing the list

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

## 1.2 Arrays only | Subsetting by masking

In [16]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

np_array[my_mask] # Swap the results from true/false to the actual values in the array
np_array[~my_mask]  # Using the negation operator to get values that do

array([1, 2, 3])

In [ ]:
np_array[np_array > 3]
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([ 4,  5,  6,  7,  8,  9, 10])

In [18]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [19]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [20]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [23]:
py_list_2d[3][0]
np_array_2d[3, 0]

np.str_('4')

In [35]:
py_list_2d[:3][2]


[3, 'C']

In [30]:

np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U21')

In [32]:
np_array_2d[:,0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [36]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [37]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [38]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [39]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [40]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [41]:
x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [45]:
a=(1, 2, 3)     # Define tuple
print(a[0])    # Access data

# Tuples are immutable, so you cannot change their values

1


In [44]:
# The following will NOT work
a[0]=-1
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [46]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [48]:
x=[1, 2, 3]
y=x.copy() # Do this instead!
z=x.copy() # Do this instead!

## Footnotes