<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [2]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

In [4]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

print(py_super_names)
print(py_real_names)

['Black Widow', 'Iron Man', 'Doctor Strange']
['Natasha Romanoff', 'Tony Stark', 'Stephen Strange']


In [5]:
np_super_names = np.array(["batman","superman","green lantern"])
np_real_names = np.array(["no idea","wowow","idkdikdkikd"])

print(np_super_names)

['batman' 'superman' 'green lantern']


In [16]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange",
    "Spiderman": "Tom Holland"
}




superhero_info["Natasha Romanoff"]
superhero_info.keys()
superhero_info.values()


dict_values(['Black Widow', 'Iron Man', 'Doctor Strange', 'Tom Holland'])

In [12]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

py_real_names[0]
py_super_names[-3]

'Black Widow'

## 1.1 Let’s compare

## 1.2 Accessing data from a list (or array)

## 1.3 Accessing data from a dictionary

## 1.4 Higher dimensional lists

In [25]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

py_superhero_info[0][0] # Accessing the first superhero's real name
py_superhero_info[0][1] # Accessing the first superhero's super name
py_superhero_info[0] # Accessing the first superhero's full info


['Natasha Romanoff', 'Black Widow']

# 2 Lists vs. Arrays

## 2.1 Size

In [26]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [30]:
len(py_list_2d)  # Length of the Python list
len(np_array_2d)  # Length of the NumPy array
np_array_2d.shape  # Shape of the NumPy array

(10, 2)

## 2.2 Arrays are fussy about type

In [31]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [33]:
py_list
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [34]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [37]:
np_array + 10


array([11, 12, 13, 14, 15])

In [38]:
py_list + 10 # This will raise an error because you cannot add an integer to a list directly

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [39]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [40]:
py_list_1 + py_list_2 

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [41]:
np_array_1 + np_array_2 

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [42]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [43]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [44]:
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [45]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [46]:
py_list**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [47]:
np_array**2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [5]:
py_list = [1, 2, 3, 4, 5]
py_list_2 = 3
np_array = np.array(py_list)         

In [9]:
py_list == 3

False

In [8]:
py_list_2 == 3

True

In [51]:
np_array == 3

array([False, False,  True, False, False])

In [52]:
np_array >3

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [10]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [14]:
sum(py_list)     # sum() is a base Python function


15

In [15]:
max(py_list)     # max() is a base Python function

5

In [16]:
min(py_list)     # min() is a base Python function

1

In [22]:
np_array.sum()
np_array.max()
np_array.min()
np_array.mean()  # Mean of the NumPy array
np_array.std()   # Standard deviation of the NumPy array

np.float64(1.4142135623730951)

## Footnotes